name: Setup Node
description: Setup Node.js and pnpm

runs:
  using: "composite"
  steps:
    - name: Read versions from package.json
      id: versions
      shell: bash
      run: |
        NODE_VERSION=$(jq -r '.engines.node' package.json)
        PNPM_VERSION=$(jq -r '.packageManager | split("@")[1]' package.json)
        echo "NODE_VERSION=${NODE_VERSION}" >> $GITHUB_OUTPUT
        echo "PNPM_VERSION=${PNPM_VERSION}" >> $GITHUB_OUTPUT
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ steps.versions.outputs.PNPM_VERSION }}
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.versions.outputs.NODE_VERSION }}
        cache: "pnpm"
        cache-dependency-path: pnpm-lock.yaml
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
